### ISSUE TITLE
Please explain the AddOn ID

### ISSUE THREAD

**Issue by drmikecrowe** [anxdpanic/script.trakttokodi.libconn#1]
> Set the Add-on ID in TraktToKodi to script.trakttokodi.libconn

How?  The TraktToKodi addon has not configuration options

**Comment by anxdpanic** [comment]
The trakttokodi extension, click the extensions icon(near the address bar) and under Profiles. You'll see where to place the kodi ip and the spot for the add-on id.

**Comment by drmikecrowe** [comment]
Right, but what is the "Add-on ID"?  Does that come from Kodi somehow?

**Comment by anxdpanic** [comment]
for this add-on its. script.trakttokodi.libconn

**Comment by drmikecrowe** [comment]
Hmm, still nothing.  What port?  The HTTP port?  I've tried boht 8080 and 9090 and neither seem to work

**Comment by anxdpanic** [comment]
Requires you to enable another setting in Kodi
Kodi setting: Settings -> Services -> Remote Control -> Allow remote control by programs on other systems
Port will be 9090   (changing it requires changes to advancedsettings.xml so you'd know if it was different)

**Comment by drmikecrowe** [comment]
Oh, I'm starting to understand.  This looks for a play link on the Tract page and then feeds it to kodi, right?

I somehow thought it would take a title and feed it to an Exodus/Covenant type program as a search

**Comment by anxdpanic** [comment]
The extension sends content identifiers from trakt to an add-on in kodi. The add-on then uses those identifiers to play content. 
This particular add-on is for items in the kodi library, where https://github.com/anxdpanic/script.trakttokodi.embycon is for items from the embycon(emby) add-on.

**Comment by drmikecrowe** [comment]
I see. So if I in browsing Trakt and have that particular episode or movie
available in my Kodi library, this will play that. Or if I have Emby
installed, it could play that is well.

 Would you consider connecting to one of the streaming searches like
covenant and firing off a search for that particular title?

 Sorry for my confusion.

**Comment by anxdpanic** [comment]
No worries, and yes. Emby itself would use the library one(this one) since it adds all the content to library and embycon (add-on to access emby) would require the other.

I won't support any [banned add-ons](http://kodi.wiki/view/Official:Forum_rules/Banned_add-ons).
Anyone can make an add-on to use the extension, the end-points are documented [here](https://github.com/anxdpanic/TraktToKodi-Extension/wiki/Addon-Endpoints).
